worker_processes auto;
pid /run/nginx/nginx.pid;

events {
    worker_connections 512;
}

http {
    include /etc/nginx/mime.types;
    default_type text/html;
    server_tokens off;
    access_log /dev/stdout;
    error_log /dev/stderr warn;
    client_body_temp_path /var/cache/nginx/client_temp;
    proxy_temp_path /var/cache/nginx/proxy_temp;
    fastcgi_temp_path /var/cache/nginx/fastcgi_temp;
    uwsgi_temp_path /var/cache/nginx/uwsgi_temp;
    scgi_temp_path /var/cache/nginx/scgi_temp;

    server {
        listen 8080;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
    }
}
